# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=400)),
                ('password', models.CharField(default='NULL', max_length=140)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
