# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(blank=True)),
                ('checkout', models.DateField(blank=True)),
                ('firstname', models.CharField(max_length=140)),
                ('middlename', models.CharField(max_length=140)),
                ('lastname', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=400)),
                ('city', models.CharField(max_length=140)),
                ('state', models.CharField(max_length=140)),
                ('zipcode', models.IntegerField()),
                ('idproof', models.CharField(max_length=140)),
                ('rooms', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'roombooking',
            },
        ),
    ]
