# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_roombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
