# Generated by Django 2.0.4 on 2018-11-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181129_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
