# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181129_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
