# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181129_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='checkin',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='checkout',
            field=models.CharField(max_length=140),
        ),
    ]
