# Generated by Django 2.0.4 on 2018-11-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181129_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='checkin',
            field=models.CharField(default='NULL', max_length=140),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='checkout',
            field=models.CharField(default='NULL', max_length=140),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
