# Generated by Django 2.0.4 on 2018-11-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181129_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='id',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='bookingid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='roombooking',
            table='roombook',
        ),
    ]
