# Generated by Django 2.0.4 on 2018-11-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181129_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
