# Generated by Django 2.0.4 on 2018-11-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_roombooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('bookingid', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('checkin', models.CharField(default='NULL', max_length=140)),
                ('checkout', models.CharField(default='NULL', max_length=140)),
                ('firstname', models.CharField(max_length=140)),
                ('middlename', models.CharField(max_length=140)),
                ('lastname', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=400)),
                ('city', models.CharField(max_length=140)),
                ('state', models.CharField(max_length=140)),
                ('zipcode', models.IntegerField()),
                ('idproof', models.CharField(max_length=140)),
                ('rooms', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'roombooking',
            },
        ),
    ]
