# Generated by Django 2.0.4 on 2018-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181129_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
